### ISSUE TITLE
please help me, can not normally install

### ISSUE THREAD

**Issue by metalbug** [hexator/live4chan#11] opened 2016-02-13 13:16 UTC
What version of NODEJS and NPM support is needed?

**Comment by metalbug** [comment] 2016-02-14 12:13
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.7.2
3 info using node@v0.10.42
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle LiveChan@0.0.1~prestart: LiveChan@0.0.1
6 silly lifecycle LiveChan@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle LiveChan@0.0.1~start: LiveChan@0.0.1
8 verbose lifecycle LiveChan@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle LiveChan@0.0.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/test/live4chan/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle LiveChan@0.0.1~start: CWD: /home/test/live4chan
11 silly lifecycle LiveChan@0.0.1~start: Args: [ '-c', 'node lib/index.js' ]
12 silly lifecycle LiveChan@0.0.1~start: Returned: code: 8  signal: null
13 info lifecycle LiveChan@0.0.1~start: Failed to exec start script
14 verbose stack Error: LiveChan@0.0.1 start: `node lib/index.js`
14 verbose stack Exit status 8
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at EventEmitter.emit (events.js:98:17)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at ChildProcess.emit (events.js:98:17)
14 verbose stack     at maybeClose (child_process.js:766:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
15 verbose pkgid LiveChan@0.0.1
16 verbose cwd /home/test/live4chan
17 error Linux 4.2.0-16-generic
18 error argv "node" "/usr/local/bin/npm" "start"
19 error node v0.10.42
20 error npm  v3.7.2
21 error code ELIFECYCLE
22 error LiveChan@0.0.1 start: `node lib/index.js`
22 error Exit status 8
23 error Failed at the LiveChan@0.0.1 start script 'node lib/index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the LiveChan package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node lib/index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs LiveChan
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls LiveChan
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by metalbug** [comment] 2016-02-14 12:14
test@ubuntu:~/live4chan$ npm start

> LiveChan@0.0.1 start /home/test/live4chan
> node lib/index.js

Missing certificate or private key
Running with insecure server
   info  - socket.io started
connect.limit() will be removed in connect 3.0
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0

module.js:340
    throw err;
    ^
Error: Cannot find module 'carrier'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/test/ircd.js/lib/server.js:24:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.42
npm ERR! npm  v3.7.2
npm ERR! code ELIFECYCLE
npm ERR! LiveChan@0.0.1 start: `node lib/index.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the LiveChan@0.0.1 start script 'node lib/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the LiveChan package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs LiveChan
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls LiveChan
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/test/live4chan/npm-debug.log

**Comment by hexator** [comment] 2016-02-15 04:28
It looks like the carrier module didn't install.

do:  npm install carrier

Then try again.

**Comment by metalbug** [comment] 2016-02-15 11:17
yes i do this npm install carrier
try again over again
and carrier inside the node_modules
still can not run npm start
please help me or you can tell me how to install, detailed, thank you very much!

**Comment by metalbug** [comment] 2016-02-15 11:24
http://stackoverflow.com/questions/35400639/how-to-install-this-nodejs-application

help me

**Comment by hexator** [comment] 2016-02-15 19:02
I think the problem is the IRC module.  I had the same problem when I forked from the original code, and turned it off because I don't need the IRC bridge.

What I think you should do is go to the "testing" branch instead of master and install that.  I've fixed a lot of those problems.  However, you will have to copy a config file.  See the readme.md in the testing branch.

**Comment by metalbug** [comment] 2016-02-16 04:37
yea thanks man, this "testing" branch it good
but Board doesn't exist :(
and How to enter the admin panel?

**Comment by hexator** [comment] 2016-02-16 06:56
There is no admin panel.  Just edit the config file to create boards.  You may also have to change some of the node.js code as well.  If you made an admin password like in the instructions, you can delete posts by typing /admin in the chat.  You'll get a popup asking for the password, then you'll see links to delete posts, etc.

This software isn't very user friendly, so expect to have to modify the source code to get something to your liking.  Since you're up and running now, I'm going to close this issue as solved.

**Closed as completed by hexator** 2016-02-16 06:56 UTC
